export const FETCH='FETCH_ALL'
export const CREATE="CREATE"
export const UPDATE='UPDATE'
export const DELETE='DELETE'
export const LIKE='LIKE'
export const setId="setId"
export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP" 
export const LOGOUT = "LOGOUT"